#ifndef KESSEL_SABACC_SHIFTTOKEN_H
#define KESSEL_SABACC_SHIFTTOKEN_H
#pragma once

enum ShiftToken {
    FREE_DRAW,
    REFUND,
    EXTRA_REFUND,
    GENERAL_TARIFF,
    TARGET_TARIFF,
    EMBARGO,
    MARKDOWN,
    IMMUNITY,
    GENERAL_AUDIT,
    TARGET_AUDIT,
    MAJOR_FRAUD,
    EMBEZZLEMENT,
    COOK_THE_BOOKS,
    EXHAUSTION,
    DIRECT_TRANSACTION,
    PRIME_SABAC
};
#endif //KESSEL_SABACC_SHIFTTOKEN_H
